### ISSUE TITLE
Not working with latest Cloudlog

### ISSUE THREAD

**Issue by ok1cdj** [tanilolli/CloudlogTCI#1]
Hi. tested with latest version from git and i got this error message to the console:

  <div id="content">
                <h1>A Database Error Occurred</h1>
                <p>Error Number: 1048</p><p>Column 'timestamp' cannot be null</p><p>INSERT INTO `cat` (`radio`, `frequency`, `mode`, `timestamp`) VALUES ('SunSDR2DX RX2', '14100000', 'CW', NULL)</p><p>Filename: models/Cat.php</p><p>Line Number: 74</p>     </div>

It is about missing time stamp, can you fix it please ?

Regards, Ondra OK1CDJ

**Comment by anthonydiiorio** [comment]
Thanks for letting me know, just published the update!

https://github.com/anthonydiiorio/CloudlogTCI/releases/tag/2021.11.0

**Comment by ok1cdj** [comment]
Thank you very much.
