### ISSUE TITLE
Not picking Moode with Thetis on DIGIU

### ISSUE THREAD

**Issue by GregTroar** [tanilolli/CloudlogTCI#3]
Hi,

Using a Hermes Lite 2 here with Thetis and while it seems to work well in general the CloudlogTCI does not seem to be picking up the mode while in DIGIU.
The mode in Cloudlog become blank.

Thanks

**Comment by anthonydiiorio** [comment]
Hi GregTroar, 

If you look at the **Hardware Interfaces** page in Cloudlog (under the callsign dropdown) the mode will display exactly as it is passed through from the TCI connection. For example:

![chrome_546MWyLx4nfxy](https://github.com/anthonydiiorio/CloudlogTCI/assets/1933848/79ec7bfd-9dfb-4038-b966-67234a255fe0)

The trouble is there is no generic digital mode in Cloudlog for DIGU/DIGL, and there is no valid generic digital mode in the official ADIF specification: [ADIF Version 3.1.4: Mode Enumeration](https://adif.org.uk/314/ADIF_314.htm#Mode_Enumeration). Likewise in TQSL for LoTW.

Unless ExpertSDR or Thetis send valid ADIF modes, they will not display on the QSO page.

The way I handle this personally is to log digital mode contacts in their respective progams and import the ADIF file when I'm done. Alternatively you can set the radio in Cloudlog to "None" and then choose the mode manually, (RTTY, PSK, SSTV, etc). 

If you use Fldigi you can send QSOs automatically with the API http://www.w1hkj.com/FldigiHelp/Cloudlog_page.html

![fldigi_547VOlP3kqIyF](https://github.com/anthonydiiorio/CloudlogTCI/assets/1933848/40fa5459-d026-40f6-8474-021b3d0467cb)

WSJT-X/JTDX can be handled automatically with this python script [anthonydiiorio/wsjt_cloudlog.py](https://gist.github.com/anthonydiiorio/6f416fc1d8178e34784fd38c97655d32)

Other tools can be found here: https://github.com/magicbug/Cloudlog/wiki/Third-Party-Tools

**Comment by GregTroar** [comment]
Thanks for your input, that is a real pity.
Yes the hardware shows perfectly DIGU or DIGL but indeed in the QSO the mode remains blank.
Ok it may still be workable as of course I will log in JTDX first and then use probably CloudlogAurora to get the QSO logged in Cloudlog.

Thanks again for your reply
